config:
  payload:
    path: "./users.csv"
    fields:
      - "enrollmentNo"
      - "password"
  target: 'http://192.168.1.6:3000'
  phases:
    - duration: 5
      arrivalRate: 221
scenarios:
  - name: 'Signin'
    flow:
      - post:
              url: '/auth/signin'
              json:
                enrollmentNo: '{{ enrollmentNo }}'
                password: '{{ password }}'
      - log: 'Response: {{ enrollmentNo }}'


